name: mcformer
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.10
  - pip=24.2
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - pip:
      - -r requirements/dev.txt
      - -r requirements/preprocessing.txt
      - -r requirements/pose.txt
      - -r requirements/analysis.txt
